### ISSUE TITLE
getConnection can not get results

### ISSUE THREAD

**Issue by zengkunliang** [vert-x3/vertx-jdbc-client#104]
### Version

* vert.x core:3.1.0
* vert.x jdbc-client:3.1.0
* jdbc driver:Oracle 11.2.0.3
* RDBMS:Oracle

### General info

* What is your jdbc driver
* What is your RDBMS server
* What is your connection string (no user/passwords please!)

### Context

JDBCClientImpl The target database is not accessible when the connection is created for the first time The getConnection function can not handle non-SqlException errors that HikariCP throws, so the request can not be returned.

**Comment by pmlopes** [comment]
@zengkunliang can you provide a stacktrace?

**Comment by ensirius** [comment]
I have fixed this by setting `acquire_retry_attempts`

**Comment by tsegismont** [comment]
Thanks @ensirius for the update
