### ISSUE TITLE
JDBCClientImpl blocks shutdown if AbstractVerticle.start(Future) fails

### ISSUE THREAD

**Issue by dgbustos** [vert-x3/vertx-jdbc-client#105]
### Version

* vert.x core: 3.4.1
* vert.x jdbc-client: 3.4.1
* jdbc driver: com.mysql.jdbc.Driver
* RDBMS: MariaDB

### General info

* What is your jdbc driver MySQL
* What is your RDBMS server MariaDB
* What is your connection string (no user/passwords please!)

### Context

The `start(Future<Void> startFuture)` method of my verticle calls `startFuture.fail()` if something goes wrong.  Before database queries are run, this causes the process to exit, at least when it is run from a fat jar.  If it fails after `JDBCClient.createShared()` is called and some queries are run, then the process does not exit.

It seems this is because the `JDBCClient`'s `ExecutorService`'s `Thread`s are not daemon.  I think the close hook (`DataSourceHolder.close()`) is not being run because the close hooks are only run when the verticle is undeployed, which doesn't happen in this case, I presume because the deployment failed.

Making my code call `JDBCClient.close()` before calling `startFuture.fail()` results in the process exiting.

### Do you have a reproducer?

No.  One is probably easy to make.

### Steps to reproduce

1. Write a verticle which calls `JDBCClient.createShared()` in its `start(Future<Void> startFuture)` method.  Running a query might be required.  At the end of the method, call `startFuture.fail()`.
2. Build the verticle into a fat jar.
3. Run the jar.

**Comment by tsegismont** [comment]
Could you try with a Vert.x core master build? (3.5.0-SNAPSHOT)

I think this PR will solve your issue:
https://github.com/eclipse/vert.x/pull/2113

2017-09-08 20:08 GMT+02:00 dgbustos <notifications@github.com>:

**Comment by dgbustos** [comment]
Yes, that seems to fix it.

**Comment by tsegismont** [comment]
@dgbustos thank you

**Comment by tsegismont** [comment]
Duplicates eclipse/vert.x#2113
