### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by gshegosh** [vert-x3/vertx-jdbc-client#111]
Since all query results are put into JsonArray at once, for queries with a lot of rows, vertx-jdbc consumes a substancial amount of RAM (in my usage, it goes above 2GB).

In addition, ResultSet.getRows() method creates a new full-sized list, doubling memory usage.

It would be nice to have a way to iterate results (preferably as JsonObjects) as they come, without storing them all in the RAM.

**Comment by tsegismont** [comment]
For large result sets you should use streaming

http://vertx.io/docs/vertx-sql-common/java/#_streaming


Le 20 oct. 2017 11:14 AM, "Grzegorz Krugły" <notifications@github.com> a
écrit :

**Comment by gshegosh** [comment]
Somehow I've skipped this part of docs. Closing the issue, then. Thanks.
