### ISSUE TITLE
rxSetAutoCommit is not available in single SQL operations

### ISSUE THREAD

**Issue by EmadAlblueshi** [vert-x3/vertx-jdbc-client#112]
### Version

* `Vert.x version 3.5.0`
* `JDBC Driver org.postgresql 42.1.4`
* `PostgreSQL 10.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit` 
* `jdbc:postgresql://localhost:5432/vertx", "****", "****"`

**Comment by tsegismont** [comment]
@EmadAlblueshi I'm not sure what you mean. Are you talking about methods like [this one](https://github.com/vert-x3/vertx-sql-common/blob/master/src/main/java/io/vertx/ext/sql/SQLOperations.java#L55)? In this case, a single operation can only run in autocommit mode.
