### ISSUE TITLE
UpdateResult#getKeys() always empty 

### ISSUE THREAD

**Issue by EmadAlblueshi** [vert-x3/vertx-jdbc-client#113]
### Version

* `Vert.x version 3.5.0`
* `JDBC Driver org.postgresql 42.1.4`
* `PostgreSQL 10.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit` 
* `jdbc:postgresql://localhost:5432/vertx", "****", "****"`

### Keys are always empty

```javascript

CREATE TABLE "X" (
    id bigserial primary key,
    body jsonb NOT NULL
);

sqlClient.getConnection(ar -> {
  if(ar.succeeded()) {
    SQLConnection conn = ar.result();
    conn.updateWithParams("INSERT INTO \"X\" (body) values (?::jsonb)", new JsonArray().add(new JsonObject().encode()), ar2 -> {
      if(ar2.succeeded()) {
        System.out.println(ar2.result().getKeys());
      } else {
        ar2.cause().printStackTrace();
      }
    });
  } else {
    ar.cause().printStackTrace();
  }
});

```

**Comment by ruslansennov** [comment]
@EmadAlblueshi By default, sql statements prepared with `Statement.NO_GENERATED_KEYS` flag. 
To change this flag you should set `SQLOptions` in `SQLConnection`, see [example test](https://github.com/vert-x3/vertx-jdbc-client/pull/98/files#diff-fb157d6edcf133363a26ed12e3740296R614)

**Comment by EmadAlblueshi** [comment]
@ruslansennov You are absolutely right. Thanks! :+1:

**Comment by jgutierreznab** [comment]
This is currently happening under vertx-mysql-postgresql-client in 3.8
