### ISSUE TITLE
UpdateResult get empty array when insert data

### ISSUE THREAD

**Issue by mscofy** [vert-x3/vertx-jdbc-client#115]
### Version 3.5.0

* vert.x core: 3.5.0
* vert.x jdbc-client:  3.5.0
* jdbc driver:3.5.0
* RDBMS:mysql

### General info

String sql = "insert into test(val) values(?);";
jdbcClient.updateWithParams(sql, params, res->{
UpdateResult res = (UpdateResult) handler.result();
			JsonArray array = res.getKeys();
			int len = res.getUpdated();
			System.out.println("len:"+len+" array:"+array.toString());
});
 I insert one data into table which has a auto increment column "id",res.geKeys() returns a empty array but update len is 1,output show "len:1 array:[]".
when in vert.x jdbc-client:  3.4.2,output show "len:1 array:[15]".
* What is your jdbc driver 
mariadb-java-client
* What is your RDBMS server 
mysql
* What is your connection string (no user/passwords please!) 
jdbc:mysql://127.0.0.1:3306/Web?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant

**Comment by EmadAlblueshi** [comment]
Kindly see https://github.com/vert-x3/vertx-jdbc-client/issues/113
