### ISSUE TITLE
Run JDBC blocking outside of Vertx executor

### ISSUE THREAD

**Issue by joao-rebelo** [vert-x3/vertx-jdbc-client#117]
Maybe this is more of a question than an actual issue..
If I understand the code, when a JDBC blocking operation is executed it goes into the Vertx Core ContextImpl -> workerPool.
  Is this the pool of thread that is handling the mainstream reactive code?
  If so, shouldn't the JDBC operations run in a different worker pool?

  I can imagine a scenario where we would have 7 cores, and I would like to have 5 threads for Vertx main (non-blocking) work pool, and a bigger workpool (20+ threads) for sync IO as JDBC.

  Is this handled like this, is this an improvement, or just a crazy idea?

**Comment by vietj** [comment]
non blocking are different event loop threads, they are not borrowed from a pool, as these threads remain the same for the lifetime of the event loop.
