### ISSUE TITLE
why "new ThreadPoolExecutor(1, 1,...)" ?  create only one thread in pool, is enough ?

### ISSUE THREAD

**Issue by hefeiyun** [vert-x3/vertx-jdbc-client#119]
### Version

source code: 

synchronized ExecutorService exec() {
      if (exec == null) {
        exec = new ThreadPoolExecutor(1, 1,
            1000L, TimeUnit.MILLISECONDS,
            new LinkedBlockingQueue<>(),
            (r -> new Thread(r, "vertx-jdbc-service-get-connection-thread")));
      }
      return exec;
    }

**Comment by vietj** [comment]
@hefeiyun this is a pool for getting connection, not using them
