### ISSUE TITLE
Autogenerated keys not present by default after an insert since 3.5.0

### ISSUE THREAD

**Issue by ekans** [vert-x3/vertx-jdbc-client#120]
### Version

* vert.x core: 3.5.0
* vert.x jdbc-client: 3.5.0

### Context

Since 3.5.0 autogenerated keys are not returned into UpdateResult so it breaks my code when updating from 3.4.2 to 3.5.0.

Now I have to pass to my SQLConnection an SQLOptions with autoGeneratedKeys to true.

For future potential breaking changes, do you have some documentation listing theses changes?

### Steps to reproduce

1. Insert data on a table with an autogenerated key
2. Retrieve the new key from UpdateResult

**Comment by pmlopes** [comment]
Fixed by: https://github.com/vert-x3/vertx-jdbc-client/commit/14aa549213afdd5bc15a6b984064176529fb8e7f
