### ISSUE TITLE
serverTimeZone=Asia/Shanghai, It doesn't work??

### ISSUE THREAD

**Issue by laudylcp** [vert-x3/vertx-jdbc-client#123]
### Version

* vert.x core: 3.5.0
* vert.x jdbc-client: 3.5.0
* jdbc driver: com.mysql.cj.jdbc.Driver,  mysql-connector-java:6.0.5
* RDBMS: mysql 5.7.16

### General info

* What is your jdbc driver
mysql:mysql-connector-java:6.0.5
* What is your RDBMS server
mysql 5.7.16
* What is your connection string (no user/passwords please!)
protected static JsonObject config = new JsonObject()
            .put("url", "jdbc:mysql://" + ip + ":" + port + "/" + dbName
                    + "?useSSL=false"
                    + "&serverTimezone=Asia/Shanghai"
                    + "&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true"
                    + "&useUnicode=true&characterEncoding=utf8")
            .put("driver_class", "com.mysql.cj.jdbc.Driver")
            .put("max_pool_size", poolSize)
            .put("user", user)
            .put("password", password);

### Problem

The datatime is 2018-01-18 14:25:09.000 in mysql database, but got datetime is: 2018-01-18 06:25:09.000.
The jdbc url had already set: serverTimezone=Asia/Shanghai, And The mysql server config file had set:
default-time_zone='+8:00'

The Code is below:

jdbcClient.getConnection(connHandler(result, connection -> {
			connection.queryWithParams(SQL_GetBy_Where, new JsonArray()
					.add(where.getImei())
					.add(where.getAlarmCode())
					.add(where.getAlarmStatus()), r -> {
				if(r.succeeded()){
					if(r.result().getNumRows() > 0) {
						logger.trace("get first alarm row: " + r.result().getRows().get(0).encodePrettily());
						JsonObject firstRow = r.result().getRows().get(0);
						result.complete(Json.decodeValue(firstRow.toBuffer(), DeviceAlarmEntity.class));
					}
					else {
						result.complete(null);
					}
				}
				else {
					result.fail(r.cause());
				}
				connection.close();
			});
		}));

Why???

Thanks for your reply!

**Comment by pmlopes** [comment]
How are you reading the time? Json encoded temporal types follow the json rfcs which mean that they are always encoded in time zone Zulu (UTC)
