### ISSUE TITLE
OSGi Bundle is Missing io.vertx.reactivex.ext.jdbc in its Exported Packages

### ISSUE THREAD

**Issue by utey** [vert-x3/vertx-jdbc-client#129]
### Version

* vert.x core: N/A (3.5.0)
* vert.x jdbc-client: 3.5.0, 3.5.1
* jdbc driver: N/A (org.hsqldb)
* RDBMS: HSQL

*** The bundle came from maven central.

### Context

When trying to use the reactivex jdbc client in an OSGi-based project, I was unable to resolve my dependencies on io.vertx.reactivex.ext.jdbc. Upon closer examination of the manifest, I noticed that
the reactivex/rxjava2 variant of the jdbc client isn't being exported. That said, modifying the manifest to include io.vertx.reactivex.ext.jdbc under the Export-Package directive was enough to fix my problem locally. The reactivex JDBCClient .class file is already included in the bundle.

### Do you have a reproducer?

Nope, just the bundle/jar file. Again, I got the bundle from maven central.

### Steps to reproduce

I'm not sure what/where the build process is, but this can be reproduced by examining the manifest of the resulting vertx-jdbc-client bundle. Under "Export-Package", groovy and rxjava 1 can be found, but not reactivex/rxjava2. 

### Extra

Thanks!

**Comment by vietj** [comment]
we have currently reworked our approach for packaging RxJava with the Vert.x component and now the integration happens in the vertx-rx-java2 artifact

**Comment by utey** [comment]
Thanks for the quick reply! I think I'm still missing something though; is there a generated osgi bundle that exports io.vertx.reactivex.ext.jdbc? The vertx-rx-java2 artifact doesn't appear to.

**Comment by pmlopes** [comment]
With vert.x 4.0.0 OSGi metadata will not be included anymore with the distributed jars.
