### ISSUE TITLE
JDBCClient::updateWithParams does not return the generated keys

### ISSUE THREAD

**Issue by rgiaccio** [vert-x3/vertx-jdbc-client#140]
### Version

* vert.x core: 3.5.3
* vert.x jdbc-client: 3.5.3
* jdbc driver: org.postgresql.Driver
* RDBMS:PostgreSQL

### General info

* What is your jdbc driver: org.postgresql.Driver 42.2.4
* What is your RDBMS server: PostgreSQL 10
* What is your connection string (no user/passwords please!): jdbc:postgresql://localhost/gandalf

### Context

I was implementing a REST service and got the following exception on insert:

```
java.lang.IndexOutOfBoundsException: Index 0 out-of-bounds for length 0
```

regarding this line:

```
  var  id = update.result().getKeys().getInteger(0);
```

The same issue (#120) has been already solved for the JDBCConnectionImpl with update 
https://github.com/vert-x3/vertx-jdbc-client/commit/14aa549213afdd5bc15a6b984064176529fb8e7f but JDBCClientImpl does not work because JDBCUpdate (and JDBCQuery) constructors are called passing null in the options (third) parameter (JDBCClient, lines 129-133):

```
  public JDBCClient updateWithParams(String sql, JsonArray in, Handler<AsyncResult<UpdateResult>> resultHandler) {
    ContextInternal ctx = (ContextInternal) vertx.getOrCreateContext();
    executeDirect(ctx, new JDBCUpdate(vertx, helper, null, ctx, sql, in), resultHandler);
    return this;
  }
```

This subsequently cause the generatedKeys flag of the prepared statement to be set to false in JDBCUpdate::prepareStatement, lines 44-81:

```
  private PreparedStatement prepareStatement(Connection conn) throws SQLException {
    if (options != null) {
    ...
    }

    generateKeys = false;
    return conn.prepareStatement(sql, Statement.NO_GENERATED_KEYS);
  }
```

### Do you have a reproducer?

I am pretty sure this can be reproduced by any call to JDBCClient::updateWithParams to a table with auto-increment keys and trying to get the generated keys back.

### Extra

I attach a fixed file that allows to set the JDBCClient options and pass them to the Update and Query constructors, which has been tested and works fine.

[JDBCClientWithOptionsImpl.txt](https://github.com/vert-x3/vertx-jdbc-client/files/2349218/JDBCClientWithOptionsImpl.txt)

A simpler fix would be to change the last line of JDBCUpdate::prepareStatement to just:

````
    generateKeys = false;
    return conn.prepareStatement(sql, Statement.NO_GENERATED_KEYS);
````

**Comment by tsegismont** [comment]
@rgiaccio thanks for reporting, I just pushed #145 to fix it
