### ISSUE TITLE
Can the client offer creation result handler?

### ISSUE THREAD

**Issue by javadevmtl** [vert-x3/vertx-jdbc-client#157]
#1 I think the creation of the client should have a creation result handler just like HttpServer has for example. Like this we can know if the DB pool was created properly.

This is independent of drivers or pools. Basically put a wrong host or port or database and then wait for the pool to fail creating the client. An exception is caught on the event loop, but there no way for us to handle it unless we wrap a generic try catch Exception around it.

The below works, but isn't very vert.xY...
```
try {
    this.client = JDBCClient.createNonShared(vertx, config);
} catch (Exception ex) {}
```
This is desirable
```
    this.client = JDBCClient.createNonShared(vertx, config, Handler<AsyncResult<Void>>);

    or Future?

    Future<JDBCClient> = JDBCClient.createNonShared(...);
```
#2 I think the creation of the underlying pool needs to be wrapped in executeBlocking(). Simply put the above scenario causes vert.x thread block warnings.

**Comment by javadevmtl** [comment]
More detail here: https://groups.google.com/forum/?fromgroups=#!topic/vertx-dev/DLdnx0Zr7wo

**Comment by tsegismont** [comment]
If there is blocking code that is not wrapped in `executeBlocking` then agreed it must be fixed.

But for the creation method, I disagree. It is very convenient to create it and let the application start without having to care if/when the database will be available.

If it is an application requirement to fail starting when the DB is not available then the application should send a simple request like `select 1` and check the result.

**Comment by javadevmtl** [comment]
Hi, I think there's a misunderstanding of the bug...

At least with the Hikari pool, if you put an invalid host or say password or basically make the connection to to the database fail, then you get an unhandled exception. So at least Hikari pool seems to eagerly create the connections.

I posted exceptions/details on the Google thread. I can post them back here if you like?

1- You can clearly see in the code, that when creating the datasourse all exceptions are caught and wrapped as RuntimeExceptions. Which I believe is what is causing the uncaught exception.
2- The blocking warnings is a byproduct of this and I'm guessing that creating the Datasourse is expensive blocking operation.
3- The pools already offer connection testing and I don't think manually testing ourselves the connection would work because the unhandled exception won't let us get to that point anyways and it is quite unfriendly thing to do from an API usage point of view.
4- Wrapping a generic try catch around the JDBCClient.createNonShared() is also not verry reactive or vert.x like.

**Comment by tsegismont** [comment]
Yes I didn't read the user group thread I only replied to the comment about the API change.

>1- You can clearly see in the code, that when creating the datasourse all exceptions are caught and wrapped as RuntimeExceptions. Which I believe is what is causing the uncaught exception.
>2- The blocking warnings is a byproduct of this and I'm guessing that creating the Datasourse is expensive blocking operation.

I didn't know Hikari eagerly creates the connections and I'll try to find out if we can prevent this.

>3- The pools already offer connection testing and I don't think manually testing ourselves the connection would work because the unhandled exception won't let us get to that point anyways and it is quite unfriendly thing to do from an API usage point of view.

Yes it is expected from a pool manager to provide connection testing. But many applications prefer not to block startup sequence because the database is not ready yet.

>4- Wrapping a generic try catch around the JDBCClient.createNonShared() is also not verry reactive or vert.x like.

Agreed. I'm not suggesting users should do this.

**Comment by tsegismont** [comment]
I can confirm that both c3p0 and Agroal (the other datasource providers) do not fail immediately if a host or port is wrong.

Hikari has a [_fail fast_](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L115) check that should be disabled.

**Comment by javadevmtl** [comment]
Ok, but what about the exceptions that are caught and wrapped as RuntimeExceptions? Will that remain the same?

**Comment by tsegismont** [comment]
I think, the JDBC client should be reworked to defer datasource initialization to the first invocation of `getConnection`.
