### ISSUE TITLE
What are the differences between a shared data source and a non shared data source?

### ISSUE THREAD

**Issue by r-mueller** [vert-x3/vertx-jdbc-client#158]
### Context
This is not an issue report but just a question.

The vertx jdbc client documentation mentions that "In most cases I will want to share a data source between different client instances". It does not explain why it is a better idea to create shared jdbc data sources.
https://vertx.io/docs/vertx-jdbc-client/java/#_using_default_shared_data_source 

What are the pros. and cons. of both methods? Are there use cases where a non shared data source is better?

Best Regards

**Comment by tsegismont** [comment]
Vert.x applications are often built using verticles. Verticles are assigned a single event loop on deployment and, to use all the cores available, you would deploy multiple instances. But when you create a pool of database connections, you often don't want each verticle to create its own pool. This is where shared data sources can help.
