### ISSUE TITLE
The Date String has been converted to the type of 'Date', this causes the execution of SQL statements to fail.

### ISSUE THREAD

**Issue by shenzhenMirren** [vert-x3/vertx-jdbc-client#170]
### Version

* vert.x core:from now 3.7.1 to 4.0.0-milestone1
* vert.x jdbc-client:from now 3.7.1 to 4.0.0-milestone1
* jdbc driver: mysql
* RDBMS:mysql

### Context
in the package io.vertx.ext.jdbc.impl.actions.JDBCStatementHelper;
function name fillStatement
line 119 --- 
![1](https://user-images.githubusercontent.com/24805209/63259011-e5ae9500-c2af-11e9-93f7-fa04fca40fa2.png)
![2](https://user-images.githubusercontent.com/24805209/63259022-eba47600-c2af-11e9-8857-de54fca98275.png)

optimisticCast

**Comment by shenzhenMirren** [comment]
![图片](https://user-images.githubusercontent.com/24805209/63259116-1d1d4180-c2b0-11e9-930c-fefc4b4b9bbe.png)

**Comment by zero88** [comment]
This should be resolved in #235 @pmlopes
