### ISSUE TITLE
implement the vertx-sql-client API

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-jdbc-client#171]
vertx-sql-client API is the new API for the reactive drivers, it is also possible to wrap an existing JDBC driver on this mode. This issue is about implementing it.

**Comment by pmlopes** [comment]
This issue depends on the discussion happening here: https://github.com/eclipse-vertx/vertx-sql-client/issues/421

**Comment by vietj** [comment]
replaced by https://github.com/vert-x3/vertx-jdbc-client/issues/187 and https://github.com/vert-x3/vertx-jdbc-client/issues/188
