### ISSUE TITLE
ClassCastException while parsing Array value

### ISSUE THREAD

**Issue by wkerckho** [vert-x3/vertx-jdbc-client#195]
Stacktrace:
```
java.lang.ClassCastException: class [D cannot be cast to class [Ljava.lang.Object; ([D and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
	at io.vertx.ext.jdbc.impl.actions.JDBCStatementHelper.convertSqlValue(JDBCStatementHelper.java:257)
	at io.vertx.ext.jdbc.impl.actions.JDBCStatementHelper.asList(JDBCStatementHelper.java:173)
	at io.vertx.ext.jdbc.impl.actions.JDBCQuery.execute(JDBCQuery.java:59)
```

### Version

4.0.0.Beta3

### Context

I use the Vertx JDBC Client for communicating with a [Clickhouse](https://clickhouse.tech/) database (using the official [JDBC driver](https://github.com/ClickHouse/clickhouse-jdbc)). I have a table that contains a Float array column that is giving me issues.

[This line](https://github.com/vert-x3/vertx-jdbc-client/blob/7cc467a08da2ecfee336f820c33e8864d337b41e/src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java#L257) in JDBCStatementHelper tries to cast values for this column to Object arrays. However, the values returned by the Clickhouse JDBC driver in this case are of type double[], thus causing a ClassCastException.

### Do you have a reproducer?

https://github.com/wkerckho/vertx-jdbc-issue

### Steps to reproduce

1. Start the Clickhouse DB using the supplied docker-compose file
2. Execute the Main class

(The docker service entry for Clickhouse uses a volume mount to supply an init script)

### Extra

JVM version: OpenJDK 14.0.1

**Comment by wkerckho** [comment]
PS: Note that the Java documentation for `java.sql.Array` specifies that implementations can choose whether to use primitive array or Object array when returning such a value.

> When getArray is used to materialize a base type that maps to a primitive data type, then it is implementation-defined whether the array returned is an array of that primitive data type or an array of Object.

Source: https://docs.oracle.com/en/java/javase/14/docs/api/java.sql/java/sql/Array.html#getArray()

**Comment by wkerckho** [comment]
FYI: I have the same issue when using Vertx 4.0.0

**Comment by vietj** [comment]
let's try fix that for 4.0.1 and then backport

**Comment by Falx** [comment]
Hi, any reason why this fix didn't make the 4.0.1, 4.0.2 and now 4.0.3 release? We could really use this fix..

**Comment by pmlopes** [comment]
@Falx can you double check please? The commit claiming to fix it: https://github.com/vert-x3/vertx-jdbc-client/commit/1f66409cf7feceeb5e67f18147aa980be878a66f was merged.

**Comment by wkerckho** [comment]
Hi Paulo,

I've updated the [reproducer project](https://github.com/wkerckho/vertx-jdbc-issue) to Vert.x 4.0.3, but I still get a ClassCastException:

```
java.lang.ClassCastException: class [D cannot be cast to class [Ljava.lang.Object; ([D and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
	at io.vertx.ext.jdbc.impl.actions.JDBCStatementHelper.convertSqlValue(JDBCStatementHelper.java:257)
	at io.vertx.ext.jdbc.impl.actions.JDBCStatementHelper.asList(JDBCStatementHelper.java:173)
	at io.vertx.ext.jdbc.impl.actions.JDBCQuery.execute(JDBCQuery.java:59)
```

**Comment by Falx** [comment]
> @Falx can you double check please? The commit claiming to fix it: [1f66409](https://github.com/vert-x3/vertx-jdbc-client/commit/1f66409cf7feceeb5e67f18147aa980be878a66f) was merged.

I see it is merged in, but the bug still remains, as you can see with the updated reproducer projectof @wkerckho

**Comment by pmlopes** [comment]
The test:

```java
  @Test
  public void simpleTest(TestContext should) {
    Async test = should.async();
    client.query("select * from arr_test")
      .execute(should.asyncAssertSuccess(res -> {
        should.assertEquals(1, res.size());
        Row row = res.iterator().next();
        should.assertEquals(new JsonObject()
          .put("id", "1ff954bb-9808-4309-9955-fccf1a26266e")
          .put("value", new JsonArray().add(0.0d).add(1.0d)), row.toJson());
      test.complete();
    }));
  }
```

Is the same as the reproducer and it seems to show that there's no error anymore. Will close the issue.

**Comment by sarcobe** [comment]
I've updated the reproducer to use Vertx 4.1.0 and the issue persists. In which version of Vertx will the fix be included?

**Comment by pmlopes** [comment]
@sarcobe I see. The difference here is that my test is using the 4.x API, while the reproducer is still using the old 3.x API. The 3.x cast code is not working correctly.

I've backported the fixes to the old API too.
