### ISSUE TITLE
Create JDBCPool by DataSourceProvider

### ISSUE THREAD

**Issue by zero88** [vert-x3/vertx-jdbc-client#230]
#### Describe the feature

Need another creator method for creating `JDBCPool` to avoid fully configuration `DataSource` by json and also reuse 2 providers from `C3P0` and `Hikari`

`static JDBCPool pool(Vertx vertx, DataSourceProvider provider)`

Beside 2 current methods

https://github.com/vert-x3/vertx-jdbc-client/blob/b21ce854bb7ce56af339e6d1e38e285a5d0d7190/src/main/java/io/vertx/jdbcclient/JDBCPool.java#L56

https://github.com/vert-x3/vertx-jdbc-client/blob/b21ce854bb7ce56af339e6d1e38e285a5d0d7190/src/main/java/io/vertx/jdbcclient/JDBCPool.java#L75

#### Contribution

I can provide PR

**Comment by vietj** [comment]
please provide a contribution

**Comment by pmlopes** [comment]
@zero88 I think we can make this simpler by just using a default method as all the functionality to support data sources is already present but not public:

```java
  /**
   * Create a JDBC pool with a user provided data source.
   *
   * @param vertx  the Vert.x instance
   * @param dataSource a user supplied datasource
   * @param connectOptions the options to configure the connection and tracing
   * @return the client
   */
  static JDBCPool pool(Vertx vertx, DataSource dataSource, JDBCConnectOptions connectOptions) {
    final ContextInternal context = (ContextInternal) vertx.getOrCreateContext();

    return new JDBCPoolImpl(
      vertx,
      new JDBCClientImpl(vertx, dataSource),
      connectOptions,
      context.tracer() == null ?
        null :
        new QueryTracer(context.tracer(), connectOptions.getTracingPolicy(), connectOptions.getJdbcUrl(), connectOptions.getUser(), connectOptions.getDatabase()));
  }
```

**Comment by pmlopes** [comment]
Here `dataSource` is a `javax.sql.DataSource` object.

**Comment by zero88** [comment]
Ya, I see @pmlopes 
But one issue is `DataSource` library will manage pool by itself, and not delegate to `Vertx`.
For example:
With `DataSource`
```
17:15:10.535 [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
17:15:10.680 [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
```

With `DataSourceProvider`
```
17:15:10.809 [vert.x-worker-thread-0] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
17:15:10.809 [vert.x-worker-thread-0] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
```

So, if put `DataSource` in vertx worker thread pool, it will be enhanced by `BlockedThreadChecker`, is it good rather than main thread?

**Comment by pmlopes** [comment]
Good point!

**Comment by zero88** [comment]
> @zero88 I think we can make this simpler by just using a default method as all the functionality to support data sources is already present but not public

@pmlopes It is related to https://github.com/vert-x3/vertx-jdbc-client/issues/228, then I can add it in PR also. How your thought?

**Comment by zero88** [comment]
ping @pmlopes
