### ISSUE TITLE
Ouput parameters not handled correctly for stored procedure.

### ISSUE THREAD

**Issue by javadevmtl** [vert-x3/vertx-jdbc-client#239]
Vertx 4.1.4 and Mm Sql Server 2016

Based on the convo here: https://mail.google.com/mail/u/0/?zx=ndqtji5gbmxf#inbox/FMfcgzGlkFpPFcrCCJdHdgCgFwLsjkdK

Procedure 1:

```
CREATE procedure [dbo].[rsp_vertx_test_1]
    @id int,
    @echo varchar(16) out
as
begin
    set NOCOUNT on    

    select * from vertx_test where id = @id
    
    set @echo = 'echo'

    set NOCOUNT off
end
go
```

Procedure 2:
```
CREATE procedure [dbo].[rsp_vertx_test_2]
    @echo varchar(16) out
as
begin
    set NOCOUNT on    
    
    set @echo = 'echo'

    set NOCOUNT off
end
go
```

Stored procedures are executed with:
```
pool.preparedQuery("{ call rsp_vertx_test_1(?, ?)}").execute(Tuple.of(1, SqlOutParam.OUT(JDBCType.VARCHAR)))
pool.preparedQuery("{ call rsp_vertx_test_2(?)}").execute(SqlOutParam.OUT(JDBCType.VARCHAR))
```

When the 1st stored procedure is executed the result of `System.out.println(rows.property(JDBCPool.OUTPUT));` is null.

For the second stored procdure when executing `System.out.println(row.toJson());` throws NullPointerException.

**Comment by pmlopes** [comment]
@javadevmtl I've added the examples above to the tests and fixed an interference that happens with the MSSQL JDBC driver when both an attempt to extract auto-generated keys and a procedure output are both in place.

The only way to get the driver to properly behave is to skip auto-generated key extraction if output parameters are registered.

**Comment by javadevmtl** [comment]
Thanks how about the second part where toJson throws NullPpointerExceeption or is it part of the same issue?

**Comment by pmlopes** [comment]
The null happens because in JDBC the callbable statement output have no metadata, so we cannot extract any label name for the synthetic row. We could however use its 1-based index as label
