### ISSUE TITLE
[regression] JDBCSQLRowStream handles DateTimeOffset type incorrectly

### ISSUE THREAD

**Issue by MYDIH** [vert-x3/vertx-jdbc-client#255]
### Version

This bug is in the tree since 4.2.0, 4.1.6 seems ok

### Context

I just tried to update from 4.0.3 to 4.2.1, when streaming a table on a MSSQL server that has a column of type DateTimeOffset, I receive a 

```java
throw new IllegalArgumentException("Type:" + type + " is not a valid Types.java value.");
```

### Do you have a reproducer?

It's quite easy to reproduce, just add a DateTimeOffset column to a MSSQL table and try to stream it using both the legacy or the new  API

### Extra

The code in question is :

4.1.6
```java
private void readBatch() {
    if (!rsClosed.get()) {
      ctx.<List<JsonArray>>executeBlocking(fut -> {
        try {
          List<JsonArray> rows = new ArrayList<>(fetchSize);
          for (int i = 0;i < fetchSize && rs.next();i++) {
            JsonArray result = new JsonArray();
            for (int j = 1; j <= cols; j++) {
              Object res = JDBCStatementHelper.convertSqlValue(rs.getObject(j)); // Seems to work properly
              if (res != null) {
                result.add(res);
              } else {
                result.addNull();
              }
            }
            rows.add(result);
          }
          fut.complete(rows);
        } catch (SQLException e) {
          fut.fail(e);
        }
      }, statementsQueue, ar -> {
        if (ar.succeeded()) {
          List<JsonArray> rows = ar.result();
          if (rows.isEmpty()) {
            empty(null);
          } else if (pending.write(rows)) {
            readBatch();
          }
        } else {
          empty(ar.cause());
        }
      });
    }
```

4.2.1
```java
private void readBatch() {
    if (!rsClosed.get()) {
      ctx.<List<JsonArray>>executeBlocking(fut -> {
        try {
          JDBCTypeProvider provider = col -> JDBCType.valueOf(metaData.getColumnType(col)); // Throws IllegalArgumentException
          List<JsonArray> rows = new ArrayList<>(fetchSize);
          for (int i = 0; i < fetchSize && rs.next(); i++) {
            JsonArray result = new JsonArray();
            for (int j = 1; j <= cols; j++) {
              Object res = decoder.parse(rs, j, provider);
              if (res != null) {
                result.add(res);
              } else {
                result.addNull();
              }
            }
            rows.add(result);
          }
          fut.complete(rows);
        } catch (SQLException e) {
          fut.fail(e);
        }
      }, statementsQueue, ar -> {
        if (ar.succeeded()) {
          List<JsonArray> rows = ar.result();
          if (rows.isEmpty()) {
            empty(null);
          } else if (pending.write(rows)) {
            readBatch();
          }
        } else {
          empty(ar.cause());
        }
      });
    }
  }
```

**Comment by zero88** [comment]
Hi, I'm the author of these changes.

Actually, this is my mistake. It should not static initialization like this
https://github.com/vert-x3/vertx-jdbc-client/blob/0baa0885573ef4b56ed425fa22ab506a12938d75/src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java#L163

It should be

```
JDBCTypeProvider provider = JDBCTypeProvider.fromMetadata(metadata);
```

**Comment by zero88** [comment]
Since `v4.2.0`, we provide `JDBCEncoder` and `JDBCDecoder` as SPI to allow developers can customize SQL data types based on the specific database and JDBC driver.

Please see this: https://github.com/vert-x3/vertx-jdbc-client/pull/235

In development time, I was only tested on H2/HSQL/PostgreSQL, so other databases might is not correct behavior. So, the developers can provide a patch for fixing this in their application.

**Comment by vietj** [comment]
can you provided a fix @zero88 ?

**Comment by zero88** [comment]
@vietj sure.
Actually, I think the document is out of date.
Need to update https://vertx.io/docs/vertx-jdbc-client/java/#_data_types based on

https://github.com/vert-x3/vertx-jdbc-client/blob/0baa0885573ef4b56ed425fa22ab506a12938d75/src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java#L44-L46
