### ISSUE TITLE
vertx-jdbc-client maven repo old(?)

### ISSUE THREAD

**Issue by qsys** [vert-x3/vertx-jdbc-client#26]
When I add

    <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-jdbc-client</artifactId>
        <version>3.0.0</version>
    </dependency>

to my pom, with version being 3.0.0, apparently being the latest version, it all works with the default (c3p0) datasource provider. However, changing to one of the two other ones (BoneCP and HikariCP), the datasourceprovider implementation cannot be found. That's pretty obvious, since they are not in the maven (yet). Will these datasource providers be added to the maven repository (e.g. in version 3.0.1)?

**Comment by cescoffier** [comment]
You should be able to get the last version using:

```
<dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-jdbc-client</artifactId>
      <version>3.1.0-SNAPSHOT</version>
</dependency>
```

the version including the new data source provider is not released yet. It will probably be part of the 3.0.1 (not decided yet).
