### ISSUE TITLE
JDBCClient client returns postgres TIMESTAMP and TIMESTAMPTZ columns in wrong format

### ISSUE THREAD

**Issue by ashertarno** [vert-x3/vertx-jdbc-client#263]
### Version

4.2.4

### Context

In version 4,2,4 JDBCClient returns columns of the types in the subject as follows:
TIMESTAMP
```
{
    "nano" : 482753000,
    "year" : 2022,
    "monthValue" : 2,
    "dayOfMonth" : 6,
    "hour" : 17,
    "minute" : 47,
    "second" : 56,
    "dayOfWeek" : "SUNDAY",
    "dayOfYear" : 37,
    "month" : "FEBRUARY",
    "chronology" : {
      "calendarType" : "iso8601",
      "id" : "ISO"
    }
  }
```
TIMESTAMPTZ
A warning is logged
```
[io.vertx.ext.jdbc.spi.JDBCDecoder]: Error when convert SQL date time. Try coerce value
org.postgresql.util.PSQLException: Cannot convert the column of type TIMESTAMPTZ to requested type timestamp. 
```
followed by response
```
{
    "offset" : {
      "totalSeconds" : 0,
      "id" : "Z",
      "rules" : {
        "fixedOffset" : true,
        "transitions" : [ ],
        "transitionRules" : [ ]
      }
    },
    "nano" : 828699000,
    "year" : 2022,
    "monthValue" : 2,
    "dayOfMonth" : 6,
    "hour" : 19,
    "minute" : 5,
    "second" : 22,
    "dayOfWeek" : "SUNDAY",
    "dayOfYear" : 37,
    "month" : "FEBRUARY"
  }
```
This looks like a regression vs version 4.1.x and earlier where the values were returned as formatted strings.

### Steps to reproduce

1. Create the following table in Postgres
```
CREATE TABLE test_table (
    name TEXT NOT NULL,
    timestamptz_column TIMESTAMP WITH TIME ZONE,
    timestamp_column TIMESTAMP
);
```
This creates the following table:
```
       Column       |            Type             | Collation | Nullable | Default
--------------------+-----------------------------+-----------+----------+---------
 name               | text                        |           | not null |
 timestamptz_column | timestamp with time zone    |           |          |
 timestamp_column   | timestamp without time zone |           |          |

```
2. Insert a row of data
`insert into test_table (name, timestamptz_column, timestamp_column) values ('test1', now(),  now());`

3. Read a row with a JDBCClient
```
JDBCClient jdbcClient = JDBCClient.createShared(vertx, new JsonObject().put("url", "jdbc:postgresql://xyz")
        .put("user", "xyz")
        .put("password", "xyz"));
jdbcClient.rxGetConnection().flatMap(conn -> conn.rxQuery("select name, timestamptz_column , timestamp_column from test_table "))
            .map(ResultSet::getRows)
            .flattenAsFlowable(r -> r)
            .subscribe(json -> System.out.println(json.encodePrettily()), Throwable::printStackTrace);
```

### Environment

CentOS8
jdk11
PostgreSQL 10.7

**Comment by ashertarno** [comment]
@vietj it seems that adding jackson-datatype-jsr310 dependency to the project and adding
```
static {
    DatabindCodec.mapper().findAndRegisterModules()
        .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false).configure(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false);
    DatabindCodec.prettyMapper().findAndRegisterModules()
        .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false).configure(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false);
  }
```
solves the issue. 
i am not closing this yet, idk if this workaround is the way to go or this is a regression that should be handled internally in vertx. thanks.

**Comment by tsegismont** [comment]
@ashertarno please take a look at https://github.com/vert-x3/vertx-jdbc-client/issues/248#issuecomment-1058222890

In your case, I think you could override the `decodeDateTime` method:

```java
  public static class CustomDecoder extends JDBCDecoderImpl {

    @Override
    protected Object decodeDateTime(SQLValueProvider valueProvider, JDBCColumnDescriptor descriptor) throws SQLException {
      // your custom date time decoding
    }
```

@pmlopes @zero88 can you confirm?

**Comment by zero88** [comment]
@tsegismont Yep, correct. 
@ashertarno you can add your SPI decoder to resolve this case. However, actually, I don't understand why this ticket title is `wrong format in TimeStamp and Timestamptz`. 
Currently, TimeStamp will be converted to LocalDateTime and Timestampz will be converted to OffsetDateTime

**Comment by zero88** [comment]
Btw, when reviewing a code in [this part](https://github.com/vert-x3/vertx-jdbc-client/blob/6d186d64fabbd71f492cba051adee8cf8902776a/src/main/java/io/vertx/ext/jdbc/spi/impl/JDBCDecoderImpl.java#L178-L186), this is my mistake, `java.sql.Time` and `java.sql.Timestamp` values are converted to incorrect `OffsetTime` and `OffsetDateTime` value.
For example: 
PostgreSQL value: `2017-05-14 23:59:59-03` => output `2017-05-15T09:59:59Z` (my local timezone is `+7`)
The correct value should be: `2017-05-15T02:59:59Z`
I will provide a fix in this weekend.

**Comment by ashertarno** [comment]
@zero88 i described the regression vs previous versions in my example. look at the json generated in the query response. instead of a formatted string we get a json object, probably serialized  OffsetTime representation by jackson obectmapper indeed. the way it worked previously makes much more sense to me: i expect the json to hold the values as DB query would return them without any additional java specific parsing logics applied.  this change also breaks some mix orm-vertx solutions like vertx-jooq etc. 
btw, how does the same work now in ither languages,  js for example?

**Comment by zero88** [comment]
@ashertarno oh, I got it. I have missed this line
> This looks like a regression vs version 4.1.x and earlier where the values were returned as formatted strings.

Since version 4.2, `vertx-jdbc` relies on the JDBC 4.2 specification as [the official document](https://vertx.io/docs/vertx-jdbc-client/java/#_data_types). Then I think you have 2 ways to fix it:
- Use `jackson-datatype-jsr310` as your workaround to convert `timestamp with timezone` to `string` when retrieving JSON data. But the actual data in `result set` still be as `OffsetDateTime`
- Provide `CustomJDBCDecoder` to handle `timestamp with timezone` column globally in your project. You can map to string as you need.
For `vertx-jooq`, as I remembered, it generates the `VertxPojo` by jooq and you can customize the generator to remap the column from OffsetDateTime to String.

**Comment by zero88** [comment]
> btw, how does the same work now in other languages, js for example?

@vietj @tsegismont can you confirm it?

**Comment by tsegismont** [comment]
>> btw, how does the same work now in other languages, js for example?
>
>  @vietj @tsegismont can you confirm it?

Javascript is no longer supported in Vert.x 4. Only Kotlin and Groovy.

**Comment by ashertarno** [comment]
closing this since it wasn't really a bug but rather a functional backwards incompatible change between the versions.

**Comment by tsegismont** [comment]
Changing label to `invalid` to make the release notes program happy.
