### ISSUE TITLE
Make agroal the new default pool implementation

### ISSUE THREAD

**Issue by tarvfx** [vert-x3/vertx-jdbc-client#264]
#### Describe the feature

Hi @vietj,
`c3p0` dependency is not required. Its development has stalled.  I think it can be `optional`.
![image](https://user-images.githubusercontent.com/70388114/155488748-0989ec64-df3a-403a-9611-dedc0e2d404b.png)

Give the simplest and best explanation.

#### Use cases

A list of use cases this feature will enable and the value it creates.

#### Contribution

Who should implement this feature ? are you volunteering for implementing this feature or
do you know that is able and willing implement this feature ?

**Comment by vietj** [comment]
@pmlopes

**Comment by pmlopes** [comment]
@vietj `c3p0` was the "default" pool. Given that most pools are being deprecated, should we decide to make the new default `agroal`? It's the simplest one, I believe.

**Comment by vietj** [comment]
we can discuss that for a next dot release

**Comment by pmlopes** [comment]
Yes, I've doubled checked agroal and it seems the latest 2.x release requires java 11 which would be incompatible with the current minimum java version for vert.x 4.x

**Comment by vietj** [comment]
ok thanks for reporting.

**Comment by tsegismont** [comment]
Closing, in Vert.x 5 the JDBC Client will use the pool implemented in `vertx-sql-client`.
