### ISSUE TITLE
SQL generator

### ISSUE THREAD

**Issue by Xpecya** [vert-x3/vertx-jdbc-client#270]
Hello Vert.x.

I DO appreciate your job and I'm now using Vert.x in my project.
Currently when I'm using vertx-jdbc-client, I always need to write a SQL generator myself, based on StringBuilder or Mybatis or Hibernate etc. I've tried all of them and some of them work well, but I still want one from Vert.x as none of them is a pure SQL generator, and none of theirs' main propose is to generate SQL only, so I'm asking if Vert.x is willing to start a new project for generating SQL, or add a new feature for this in vertx-jdbc-client? Well In my opinion this should be a new project because it will also be needed for other Vert.x projects like vertx-mysql-client, vertx-mssql-client and vertx-postgresql-client etc. 

Thank you.

#### Describe the feature

Make something like JPA or mybatis SQL generator(org.apache.ibatis.jdbc.SQL e.g.) to help user generate sql statement/prepared statement. 

#### Use cases

Every time when jdbc is needed

#### Contribution

I'm volunteering for this feature if you guys agree to add this to your project.

**Comment by tsegismont** [comment]
Have you tried [`vertx-jooq`](https://github.com/jklingsporn/vertx-jooq) ? cc @jklingsporn

**Comment by Xpecya** [comment]
@tsegismont Well It's not found in https://vertx.io so I missed this. I searched this project on github and it seems that it is not for projects such as vertx-mysql-client, vertx-mssql-client etc... Yeah it is indeed something like what I'm looking for. Maybe I should open a issue in their project LOL.
BTW, will vertx-jooq be part of the Vert.x project? I mean will you put that projecct on https://vertx.io?

**Comment by tsegismont** [comment]
It's a community project, not supported by the Vert.x core team. But it does work with `vertx-mysql-client` or `vertx-mssql-client`.

**Comment by Xpecya** [comment]
nice! thx dude
