### ISSUE TITLE
Add a way to set client information to sql connections

### ISSUE THREAD

**Issue by miggonaut** [vert-x3/vertx-jdbc-client#280]
#### Describe the feature

`java.sql.Connection` gives you the ability to set "client information", [see JavaDoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Connection.html#setClientInfo(java.lang.String,java.lang.String)).
Connections provided by vertx do not have this feature, neither for `io.vertx.ext.sql.SQLConnection` nor for `io.vertx.ext.jdbc.impl.JDBCConnectionImpl`.
Also nice would be a way to set "default" client information for the `JDBCClient`, since i dont get access to the connection if i use `JDBCClient#query` for example

#### Use cases

For non vertx projects we use this to assign information supported by our database, which for example are the formal and technical name of the program that executed a statement as well as the user, which often is not the technical user that is used to get database access. This can be used as an easy way to add audit information to created or edited table entries via generated columns.

**Comment by mfvald** [comment]
Hello, is it possible to request a rough estimate on when(if?) this feature will be available?

Apoligies for having a post of this nature as my first here, very quick reasoning for the inquiry: I work in a team in a ~ 750 ppl company, our team have been using vert.x for roughly 2.5 years. Our central db2 teams has however,  decided that clientinfo is a mandatory field from 15th of September(test envs) and 15th. of November in production environments.

I want to determine if it reasonable to wait for an upcomming release, or if we need to schedule resources on a workaround.

**Comment by vietj** [comment]
can you show which databases actually supports this ?

**Comment by mfvald** [comment]
Not entirely sure what you mean by "show"?

But it is supported by IBM DB2(z/Os).

https://www.ibm.com/docs/en/db2/11.5?topic=pecidscip-client-info-properties-support-by-data-server-driver-jdbc-sqlj

I was following a similiar threat with regards to implementing an unWrap to expose the underlying java.sql.connection. Which seemed to be what we need.

https://github.com/eclipse-vertx/vertx-sql-client/issues/1088

but it seems to have stranded with the request for a new PR.

**Comment by vietj** [comment]
I'm wondering about the support for this for other SQL client implementations that don't wrap JDBC as it seems interesting

**Comment by vietj** [comment]
@mfvald have you tried to build a JDBC pool using

```java
  static JDBCPool pool(Vertx vertx, DataSource dataSource) {
    return pool(vertx, DataSourceProvider.create(dataSource, new JsonObject()));
  }
```

this way you can provide your own `DataSource` and make sure connections use the correct user info.

**Comment by vietj** [comment]
I'll provide a way to unwrap to a JDBC connection at least soon.

**Comment by vietj** [comment]
it seems actually those info must be set before connecting ?

**Comment by vietj** [comment]
it seems that with DB2, it should work according to https://www.ibm.com/docs/en/db2-for-zos/12?topic=jies-providing-extended-client-information-data-source-client-info-properties

properties can be set after a connection has been created, info must be set before executing the first statement.

**Comment by vietj** [comment]
it seems also it can be used after connecting with PostgreSQL, so it seems reasonable to provide a static helper that unwraps the SQL connection to a JDBC connection.

as for having an initiliazer, it seems complicated to do, because the vertx pool is wrapping a JDBC pool and there is no way to know when a JDBC connection has been created or not by the pool.

**Comment by mfvald** [comment]
You last two comments have pretty hit our use case spot on.

we need custom client info for the invididual connections, and not all created from the pool.

I haven't tried creating a custom JDCPool, but as far as i can tell, and it seems you reached the same conclusion, it won't actually be useful for our use case.

**Comment by vietj** [comment]
can you elaborate when the client info would be set and how ideally ?

**Comment by mfvald** [comment]
It is fairly straight forward(..for me..atleast;-))

Should probably mention we are on vertx. 4.1.5 atm.

We use a `JDBCPool `to draw a connection which is kept and reused for the duration of our transaction scope, which is manually managed.

We have a custom Transaction scope object of sorts which given a `JDBCPool `can be initialized to prepare a io.vertx.sqlclient.SqlConnection`

On preparation of this connection and scope we ideally would like to do something like:
```
...
openConnection(pool) //calls pool.getConnection etc
     .onComplete(conn -> 
         conn.unwrap().setClienInfo("ClientUser", corrId);
     );
...
```

The field is used to propagate a correlation id to DB2 to help track usage by individual transactions.

Due to the nature of the company i work at(financial) i can't really divulge any implementation details without breaking company policy.

**Comment by vietj** [comment]
@mfvald unless I'm wrong the new unwrap method should work for you ?

**Comment by vietj** [comment]
note JDBC in Java >= 9 has a new `ConnectionBuilder` that seems useful for initialising connections and shows some potential

**Comment by mfvald** [comment]
Am i missing something here?

io.vertx.ext.sql.SQLConnection has an unwrap method. (used by the old vert.x 3.x.x jdbc client)
but 
in my 4.3.3 dev branch,  io.vertx.sqlclient.SqlConnection does not(Used by vert.x.4 JDBCPool)

As far as i can tell these two classes are not interchangeable.

**Comment by vietj** [comment]
I meant with https://github.com/vert-x3/vertx-jdbc-client/issues/285

**Comment by mfvald** [comment]
ah, sorry, i apparently only read the first line of that post.
So i did miss something;-)

yes, as far as i can tell that will be perfect.

**Comment by vietj** [comment]
thanks @mfvald we'll see if we can provide better hooks when Vert.x uses Java 9 and a more recent JDBC version

**Comment by vietj** [comment]
I'll close this issue in the meantime.
