### ISSUE TITLE
Broken type handling logic with Oracle Database in Vert.x 4.3.5+.

### ISSUE THREAD

**Issue by u-ways** [vert-x3/vertx-jdbc-client#309]
Hello, I am sharing a demo of broken type handling logic with Oracle Database in Vert.x 4.3.5+ JDBC client.

### Version

`4.4.5`

### Context

It seems that 4.3.5 has introduced broken logic when it comes to certain type handling (e.g. UUID, TIMESTAMP) with Oracle Database with the JDBC client.

As other users has reported in https://github.com/vert-x3/vertx-jdbc-client/issues/295, this is caused by the `JDBCPreparedQuery.fillStatement` method that has been changed to use the `preparedStatement.getParameterMetaData()` to work out parameter types. However, it's important to note I have noticed this applied for other types (e.g. valid TIMESTAMP formats)

### Do you have a reproducer?

Yes, a Java 17 project with a containerised database service has been created with multiple test scenarios. See: 
- [u-ways/broken-4.3.5-vertx-jdbc-client-oracle](https://github.com/u-ways/broken-4.4.5-vertx-jdbc-client-oracle)

The project contains testing code that will demonstrate the issue. Those tests can be found here:
- [io.github.u.ways.DataTypesHandlingScenariosTest](https://github.com/u-ways/broken-4.3.5-vertx-jdbc-client-oracle/blob/main/src/test/kotlin/io/github/u/ways/bugs/DataTypesHandlingScenariosTest.kt)

Tests that fail with 4.3.5, will have the comment: `// FIXME: FAILS WITH 4.3.5`.

### Steps to reproduce

See README in project to run the automated tests to reproduce the issue.

**Comment by tsegismont** [comment]
Closing, if you need special handling of specific columns, use a custom encoder/decoder

**Comment by tsegismont** [comment]
Duplicates #295
