### ISSUE TITLE
JPA Support

### ISSUE THREAD

**Issue by guedouarj** [vert-x3/vertx-jdbc-client#38]
Hello,

Thank you for your great work, I was wondering if it is possible to use JPA/Hibernate with vertx instead using native SQL in jdbc ?
I saw this: https://github.com/aesteve/vertx-hibernate-service

But I don't know if it is stable enough to really use it...

**Comment by pmlopes** [comment]
jdbc client is a small wrapper around the JDBC API, in order to support JPA you should consider create a new module such as the Hibernate one
