### ISSUE TITLE
Unhandled Runtime exception in Connection and Action scope

### ISSUE THREAD

**Issue by alex-inqwise** [vert-x3/vertx-jdbc-client#44]
In case if any Runtime exception occurred in JDBCConnection or JDBCAction scope, no have abbility to catch it. Example:

```
public class JdbcUnhandledExTest {

	public static void main(String[] args) {
		JsonObject config = new JsonObject()
			      .put("url", "jdbc:hsqldb:mem:test?shutdown=true")
			      .put("driver_class", "org.hsqldb.jdbcDriver")
			      .put("max_pool_size", 30);

		JDBCClient client = JDBCClient.createShared(Vertx.vertx(), config);
		client.getConnection(res -> {
		      if (res.succeeded()) {
		        SQLConnection connection = res.result();
		        
		        throwRuntimeException("my RUNTIME exception in connection scope");  
		        connection.queryWithParams("call some_sp(?,?)", new JsonArray().add("param1").add("param2"), res2 -> {
	  		          if (res2.succeeded()) {
	  		        	throwRuntimeException("my RUNTIME exception in JDBC action scope");	  		        
	  		          } else {
	  		        	  System.err.println(res2.cause().toString());
	  		        	  Vertx.vertx().close();
	  		          }
	  		    });
		      } else {
		    	  System.err.println(res.cause().toString());
		    	  Vertx.vertx().close();
		      }
		});
	}

	private static void throwRuntimeException(String details){
		throw new RuntimeException(details);
	}
}
```

**Comment by pmlopes** [comment]
if you have code that throws exceptions or can cause runtime exceptions you should try catch yourself. for example, in your code, if the jdbc client catches these exceptions what should it do with them? there is no parent context to pass since you're already in the response handler code.

**Comment by alex-inqwise** [comment]
No problem to catch exception. But our word not ideal and we have bugs. User experience in case of unhandled exceptions is very bad when you run as web application; Actual working thead has been "lost" and the visitor get timeout exception from his browser. As alternative, we need some mechanism to catch all unhandled exceptions occured in vertx.

**Comment by pmlopes** [comment]
the problem here is that the programing model is async/reactive so when we would catch the exception there is no proper context to handle it, there is no handler to be called at that moment, and vertx has no knowledge what should be be behavior of your application.

**Comment by alex-inqwise** [comment]
So, lets handle runtime exceptions :-)

**Comment by pmlopes** [comment]
Vert.x is unopionated so you are responsible to handle your own exceptions. Alternatively if you want better error control I'd suggest to look into RX api.

**Comment by alex-inqwise** [comment]
No problem. Currently you handle only SqlExceptions -> So as patch, I handle all Throwables and rethrow as SqlException. :-(
