### ISSUE TITLE
JDBCCallable and OUT parameters not working properly with Oracle Driver

### ISSUE THREAD

**Issue by fldrog** [vert-x3/vertx-jdbc-client#48]
I tested this using version 3.2.1 with JDBCUpdate class patch for https://github.com/vert-x3/vertx-jdbc-client/issues/46 fix. Also I used the last version of JDBCStatementHelper

The problem:

Assume you have an ORACLE table 

CREATE TABLE "SCHEMA"."TABLE"
    (    "ID" NUMBER(18,0),
         "COL1"  VARCHAR2(100 CHAR),
        "COL2" NUMBER(18,0)
)
 

Also there's a sequence  SCHEMA.SEQ_TABLE

```
private String SQL_INSERT="{CALL INSERT INTO ${schema}.table t
               (ID,COL1,COL2)
  VALUES
              (SCHEMA.SEQ_TABLE.nextVAL,?,?)
  RETURNING t.ID into ?}"
  final JsonArray outputs = new JsonArray().add(JDBCType.NUMBER);
 JsonArray input = new JsonArray().add("test1").add(3);

    jdbcClient.getConnection(res -> {
            res.result().callWithParams(sql, input, outputs, rs -> {
                if (rs.succeeded()) {
                    System.out.println(rs.result().getOutput());
                } else {
                    rs.cause().printStackTrace();
                }
            });
        });

```
The result of the above code will be an exception:

java.sql.SQLException: Missing IN or OUT parameter at index:: 3
	at oracle.jdbc.driver.OraclePreparedStatement.processCompletedBindRow(OraclePreparedStatement.java:2006)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3608)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3714)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4755)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1378)
	at com.mchange.v2.c3p0.impl.NewProxyCallableStatement.execute(NewProxyCallableStatement.java:3214)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.execute(JDBCCallable.java:52)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.execute(JDBCCallable.java:34)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:52)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.lambda$execute$10(AbstractJDBCAction.java:68)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$265(OrderedExecutorFactory.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

The problem seems to be in JDBCStatementHelper line 95:

`statement.registerOutParameter(i + 1, JDBCType.valueOf((String) value).getVendorTypeNumber());`

and in JDBCCallable line 84

`Object value = statement.getObject(i + 1);`

--------
For the above sql JDBCStatementHelper will do:

```
stament.setObject(1,"test");
stament.setObject(2,3);
statement.registerOutParameter(1, JDBCType.valueOf("NUMBER").getVendorTypeNumber());
```

BUT for Oracle we should call 

`statement.registerOutParameter(**3**, JDBCType.valueOf("NUMBER").getVendorTypeNumber());`

For my project which uses OracleDriver and I always make sure the output parameters will be at the end of the sql I changed 

JDBCStatementHelper line 95 to:

`statement.registerOutParameter(in.size() + i + 1, JDBCType.valueOf((String) value).getVendorTypeNumber());`

and JDBCCallable line 84

`Object value = statement.getObject(in.size()+i + 1)`

I'll have to investigate more to find out a proper fix.

**Comment by fldrog** [comment]
I think we might have the same issues with other drivers as well. The JDBCStatementHelper assumes we have an index for IN and another one for OUT but we have to use the same index for both like below:

  ```
Connection connection = null;
 try {
         connection = getConnection();
         String query = "call GET_DETAIL_BY_PRODUCT(?, ?)";
          CallableStatement cb = connection.prepareCall(query);
//INPUT
           cb.setString(1, "bag");
//OUTPUT (we use **2** and not 1)
            cb.registerOutParameter(2, Types.VARCHAR);
```

So we might have to change the SQLConnection.callWithParams method as well cause you might have next example:

  String query = "call GET_DETAIL_BY_PRODUCT(?, ?,?)";

where:
- 1st param is an IN parameter
- 2nd param is and OUT parameter
- 3rd param is an IN paramter

So we might want to have a way to specify that in the callWithparams() method...

What do you think?

**Comment by pmlopes** [comment]
Jdbc is index based your out array should contain
```
[null, null, "Number"]
```

**Comment by fldrog** [comment]
I see now :+1: 

Thanks!

I suppose we can close this one or leave it open until some good javadoc is added to callWithParams SQLConnection method

**Comment by pmlopes** [comment]
see: https://github.com/vert-x3/vertx-sql-common/pull/20

**Comment by fldrog** [comment]
Nice! 

Thanks!

**Comment by tunovic** [comment]
Is there no better way to have the stored procedure support with Oracle Driver? It took me quite some to find this out resulting in #135

**Comment by vietj** [comment]
we can test with oracle using Docker.

can you provide a PR with a test for this, and then we will use Docker to run it
