### ISSUE TITLE
JDBCStatementHelper DateTime can't not support anther DateTimeFormatter

### ISSUE THREAD

**Issue by Ive4** [vert-x3/vertx-jdbc-client#57]
### Version

* vert.x jdbc-client:3.2.1

### General info

JDBCStatementHelper    line:153

### Context

why not have a dateformat config?

**Comment by pmlopes** [comment]
Because our JSON follows the standard: https://www.rfc-editor.org/rfc/rfc7493.txt

Which specifies the format for temporal types. Also later on you can do `json.getInstant("your_temporal_field")` and get the java instant object.

**Comment by Ive4** [comment]
thanks
