### ISSUE TITLE
[vert.x jdbc-client: 3.3.0] java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr…'

### ISSUE THREAD

**Issue by huynhduy9988** [vert-x3/vertx-jdbc-client#67]
### Version

* vert.x core: 3.3.0
* vert.x jdbc-client: 3.3.0
* jdbc driver: 6.0.2, 6.0.3, 5.1.39
* RDBMS: MySQL, character set utf8mb4, collation utf8mb4_general_ci

### Problem
- I insert new record in MySQL table with character set utf8mb4, collation utf8mb4_general_ci then get error "java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr…'"
- Stackoverflow reference: http://stackoverflow.com/questions/15063635/java-sql-sqlexception-incorrect-string-value-xac-xed-x00-x05sr?lq=1
- I had never get this error in previous vertx version (3.2.1)
- I revert vertx 3.2.1 and everything work
- Please help me fix

**Comment by pmlopes** [comment]
Can you show the string you're trying to insert?

**Comment by huynhduy9988** [comment]
@pmlopes: 
- I sure the raw string have not any special character.
- I revert vertx 3.2.1 and everything work with sample data

**Comment by pmlopes** [comment]
@huynhduy9988 but can you provide a sample string just to have some reproducer. It does not need to be a full database just a string that causes the issue.

**Comment by huynhduy9988** [comment]
@pmlopes: 
-- Table 
CREATE TABLE `test` (
  `autoId` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID` varchar(36) NOT NULL,
  `user` varchar(20) NOT NULL DEFAULT ''
	PRIMARY KEY (`autoId`),
    UNIQUE KEY `id_UNIQUE` (`ID`),
	KEY `MUSER` (`user`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

-- Store procedure
CREATE DEFINER=`root`@`%` PROCEDURE `sp_test_INSERT`(
    p_ID                	varchar(36)     ,
	p_user              	varchar(20)
)
BEGIN
 INSERT INTO test
         (
   			ID                ,
			user              
         )
    VALUES 
         ( 
			p_ID                ,
			p_user              			
         ); 
END
-- Java code
JsonArray inParam = new JsonArray()
        .add("31cdd954-b091-4c4c-97a1-6da723d11600")
        .add("user");                

doCallWithParams("{ call sp_test_INSERT(?, ?) }", inParam, null, new Handler<AsyncResult<ResultSet>>() {
    @Override
    public void handle(AsyncResult<ResultSet> asyncResult) {
      
    }
});

-- Database info
SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
+--------------------------+--------------------+
| Variable_name            | Value              |
+--------------------------+--------------------+
| character_set_client     | utf8               |
| character_set_connection | utf8               |
| character_set_database   | utf8mb4            |
| character_set_filesystem | binary             |
| character_set_results    | utf8               |
| character_set_server     | utf8mb4            |
| character_set_system     | utf8               |
| collation_connection     | utf8_general_ci    |
| collation_database       | utf8mb4_general_ci |
| collation_server         | utf8mb4_general_ci |
+--------------------------+--------------------+
-- JDBC connection
      "url":"jdbc:mysql://localhost:3306/test_db?autoReconnect=true&useUnicode=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
      "driver_class":"com.mysql.jdbc.Driver",
      "user":"root",
      "password":"root",
      "initial_pool_size":3,
      "min_pool_size":3,
      "max_pool_size":50,
      "max_statements":500,
      "max_statements_per_connection":0,
      "max_idle_time":5,
      "database":"test_db"

**Comment by pmlopes** [comment]
this is related to: https://github.com/vert-x3/vertx-jdbc-client/issues/65
