### ISSUE TITLE
JDBC Performance - Prepared Statements, fetchSize

### ISSUE THREAD

**Issue by rozzamozza** [vert-x3/vertx-jdbc-client#75]
### Version
- vert.x core: 3.3.2
- vert.x jdbc-client: 3.3.2
- jdbc driver: Oracle 11.2.0.3
- RDBMS: Oracle
### General info
- What is your jdbc driver
- What is your RDBMS server
- What is your connection string (no user/passwords please!)
### Context

This is not a bug but a general observation on performance and getting the most out of Oracle.
Other DBs are probably much better!
1. Prepared statements are for just that - they save the overhead of having to parse sql 4each time so that they can be reused. Woul dbe great if the prepared statewment can be cached in some way to speed this up.
1. similarly Oracle is much better setting a setFetchSize(). Some way to do that would be great

**Comment by pmlopes** [comment]
Prepared statements are cached on a connection based, if you want to take advantage of it you can better use the batching feature, which will do exactly that, prepare the statement once and then run an arbitrary number of times depending on your input. This way we don't keep state outside your own handler which leads us to be memory conservative and avoid leaks. WDYT?

**Comment by rozzamozza** [comment]
Thanks Paulo - understood re not keeping round state.
Being able to set the default fetchSize or having some sort of Connection customiser woul dbe useful.
I guess we can look to do this someone how in c3p0 but if not we'll end up writing our own worker threads specific to Oracle etc.

**Comment by pmlopes** [comment]
if you want full control over the connection you could look at the data source SPI: https://github.com/vert-x3/vertx-jdbc-client/blob/master/src/main/java/io/vertx/ext/jdbc/spi/DataSourceProvider.java and write a new one that could use any of the existing connection pools and does all the setup you want before giving a connection to your vert.x code.

**Comment by NathanQuinn** [comment]
@pmlopes 
With the oracle jdbc driver, the default fetch size is set to 10 on ResultSet and PreparedStatement.  Generally speaking, we tend to set this to 50 or 100, then tune queries to appropriate other sizes when necessary.  Unfortunately, because there isn't an easy way to extend the manner in which JDBCConnectionImpl passes down its JDBCStatementHelper and JDBCConnectionImpl isn't extendable, it requires a lot of code rewriting to accomplish this goal.

For example I'd like to replace query and queryWithParams to instead use this Kotlin AbstractJDBCAction or something along these lines.  I'm not sure the best manner to achieve the goal, but it'd be great if somehow we could modify the fetchSize in a manner similar to the stream configuration.  Doing something at the data source provider level doesn't give us the granularity necessary to configure individual queries.

```
class JDBCFetchQuery(vertx: Vertx,
                     helper: JDBCStatementHelper,
                     connection: Connection,
                     ctx: ContextInternal,
                     statementsQueue: TaskQueue,
                     val timeout: Int,
                     val sql: String,
                     val input: JsonArray,
                     val fetchSize: Int = 50) :
        AbstractJDBCAction<ResultSet>(vertx, helper, connection, ctx, statementsQueue) {

    fun ResultSet.applyNextResults(statement: PreparedStatement): ResultSet {
        if(statement.moreResults){
            statement.resultSet.use { rs ->
                next = helper.asList(rs)
            }
            next.applyNextResults(statement)
        }

        return this
    }

    override fun execute(): ResultSet? {
        conn.prepareStatement(sql).use { statement ->
            if (timeout >= 0) {
                statement.queryTimeout = timeout
            }

            statement.fetchSize = fetchSize

            helper.fillStatement(statement, input)

            return if(statement.execute()) {
                statement.resultSet.use { rs ->
                    helper.asList(rs)
                }.applyNextResults(statement)
            } else {
                null
            }
        }

    }

    override fun name(): String {
        return "query"
    }
}
```

**Comment by pmlopes** [comment]
@rozzamozza we're discussing improvements to the API: https://groups.google.com/forum/#!topic/vertx-dev/TROkyJQRJIU we could try to have:

```java
select(String sql, Handler callback)
select(String sql, JsonObject params, Handler callback)
select(String sql, JsonObject params, JsonObject options, Handler callback)
```

Where the last jsonObject/DataObject could be used to pass any config to the statement such as:

* fetchSize
* timeout
* maxRows
* return keys etc...

WDYT?

**Comment by pmlopes** [comment]
https://github.com/vert-x3/vertx-jdbc-client/pull/98 covers all the options on the comment above:

* fetchSize
* timeout
* return keys
* fetchDirection
* catalog
* schema
* tx isolation

So we can keep adding more stuff in the future without breaking the API

**Comment by laiweiwei** [comment]
> #98 covers all the options on the comment above:
> 
> * fetchSize
> * timeout
> * return keys
> * fetchDirection
> * catalog
> * schema
> * tx isolation
> 
> So we can keep adding more stuff in the future without breaking the API

Why drop the `maxRows` option ?

**Comment by laiweiwei** [comment]
https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java#L242
