### ISSUE TITLE
Stabilize CI builds

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-jdbc-client#77]
A third of the builds fail on Cloudbees. Here are the common culprits:
- io.vertx.ext.jdbc.JDBCCustomTypesTest.testCustom

[#1377](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1377/)
[#1368](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1368/)
[#1393](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1393/)
[#1390](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1390/)
[#1383](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1383/)
- io.vertx.ext.jdbc.CloseTest.testUsingSharedInVerticle

[#1386](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1386/)
[#1393](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1393/)
[#1368](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1368/)
- io.vertx.ext.jdbc.CloseTest.testUsingNonSharedInVerticle

[#1378](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1378/)
[#1393](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1393/)
[#1381](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1381/)
- io.vertx.ext.jdbc.CloseTest.testUsingSharedInVerticle2

[#1366](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1366/)
[#1365](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1365/)
- io.vertx.ext.jdbc.CloseTest.testUsingNonSharedInVerticle2

[#1372](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1372/)
[#1366](https://vertx.ci.cloudbees.com/job/vert.x3-jdbc-client/1366/)

**Comment by tsegismont** [comment]
Paulo, from the last builds, it seems the issue is not resolved. I would like to reopen this ticket, unless you prefer to track failures separately.

**Comment by pmlopes** [comment]
I've added a couple more changes to the test, each test run on its own DB, if this doesn't work then we need a proper fix which is re-write the tests without using static constructor to insert test data

**Comment by tsegismont** [comment]
It seems two tests will run on the same DB, correct?


2016-11-02 16:42 GMT+01:00 Paulo Lopes <notifications@github.com>:

**Comment by tsegismont** [comment]
Missing link...

https://github.com/vert-x3/vertx-jdbc-client/commit/066b2072a0ab367f0df8a0da4b4f99235bec8404

2016-11-02 17:14 GMT+01:00 Thomas SEGISMONT <tsegismont@gmail.com>:

**Comment by pmlopes** [comment]
I mean each test suite (class file) will run on its own db, avoiding side effects across classes
