### ISSUE TITLE
Missing support for multiple result sets.

### ISSUE THREAD

**Issue by romanpa** [vert-x3/vertx-jdbc-client#80]
Current implementation of 'JDBCCallable'.execute() does not support calls to stored procedures that return multiple result sets.

Below is a current code. It is missing the usage of 'statement.getMoreResults();'.

```java
protected io.vertx.ext.sql.ResultSet execute() throws SQLException  {

    try (CallableStatement statement = conn.prepareCall(sql)) {
      if (timeout >= 0) {
        statement.setQueryTimeout(timeout);
      }

      helper.fillStatement(statement, in, out);

      boolean retResult = statement.execute();
      boolean outResult = out != null && out.size() > 0;

      if (retResult) {
        // normal return only
        try (ResultSet rs = statement.getResultSet()) {
          if (outResult) {
            // add the registered outputs
            return helper.asList(rs).setOutput(convertOutputs(statement));
          } else {
            return helper.asList(rs);
          }
        }
      } else {
        if (outResult) {
          // only outputs are available
          return new io.vertx.ext.sql.ResultSet(Collections.emptyList(), Collections.emptyList()).setOutput(convertOutputs(statement));
        }
      }
      // no return
      return null;
    }
  }
```

It should be something like:

```java
protected List<io.vertx.ext.sql.ResultSet> execute() throws SQLException {

        List<ResultSet> results = new ArrayList<>();
        try (CallableStatement statement = conn.prepareCall(sql)) {
            if (timeout >= 0) {
                statement.setQueryTimeout(timeout);
            }

            helper.fillStatement(statement, in, out);

            boolean retResult = statement.execute();
            boolean outResult = out != null && out.size() > 0;

            if (retResult) {
                while(retResult) {
                    try (ResultSet rs = statement.getResultSet()) {
                        if (outResult) {
                            results.add(helper.asList(rs).setOutput(convertOutputs(statement)));
                        } else {
                            results.add(helper.asList(rs));
                        }
                    }

                    retResult = statement.getMoreResults();
                }
            } else {
                if (outResult) {
                    results.add(new io.vertx.ext.sql.ResultSet(Collections.emptyList(), Collections.emptyList()).setOutput(convertOutputs(statement)));
                }
            }

            return results;
        }
    }
```

this is an example of stored procedure which returns multiple results:

```sql
ALTER PROCEDURE LoadSomeData
@DataID INT
AS
BEGIN
	SET NOCOUNT ON

	IF OBJECT_ID('#recs') IS NOT NULL
		DROP TABLE #recs

	SELECT
		RecordID
	INTO
		#recs
	FROM
		dbo.udfLoadKuku(@DataID)

	SELECT
		'aaaa' AS RowType,
		r.Id AS RecordID,
		r.DateFrom,
		r.DateTo,
		r.DateDue,
		r.Period,
		r.RegistrationNo,
		b.Name AS BusinessName,
		b.Address,
		r.SourceID,
		r.InternalID
	FROM
		MP_Kuku2 r
		INNER JOIN #recs ON r.Id = #recs.RecordID
		INNER JOIN Business b ON r.BusinessId = b.Id

	SELECT
		'bbbb' AS RowType,
		e.RecordId AS RecordID,
		n.Name,
		e.Amount,
		e.CurrencyCode
	FROM
		MP_Kuku3 e
		INNER JOIN #recs ON e.RecordId = #recs.RecordID
		INNER JOIN MP_Kuku4 n ON e.NameId = n.Id
	WHERE
		ISNULL(e.IsDeleted, 0) = 0

	SELECT
		'cccc' AS RowType,
		DateStart,
		DateEnd,
		AmountPaid AS PaidAmount,
		CurrencyCode AS PaidCurrencyCode,
		AmountDue AS DueAmount,
		CurrencyCode AS DueCurrencyCode
	FROM
		dbo.udfLoadKuku5(@DataID)

	DROP TABLE #recs
END
GO
```

**Comment by buddhashrestha** [comment]
I am also looking for the same feature. Is there any better solutions for this or any other workaround? 
Or, if this will be fixed or not in the future?

Trying to re-engineer the codes is really unmanageable, since the project depends upon another project (io.vertx.ext.sql), which I would not want to do.

**Comment by pmlopes** [comment]
The complicated part here is that the sql-common assumed that there was only 1 resultset and this would break the whole API. Some thinkering is needed here.

**Comment by romanpa** [comment]
Assuming that there is a modified 'JDBCCallable', which populates multiple ResultSets we can add some 'dirty' workaround, without breaking existing functionality.

Result set remains the same and gets addition, something like below:

public class ResultSet {


    private List<ResultSet> multipleSets = new ArrayList<>();


    public List<ResultSet> asMultiResultSets() {
        if (multipleSets.isEmpty()) {
            return Arrays.asList(this);
        }

        return multipleSets;
    }

    //assumes the this method is called by modified JDBCCallable
    public void addResultSet(ResultSet resultSet) {
        this.multipleSets.add(resultSet);
    }

}

**Comment by buddhashrestha** [comment]
Hmm... I might be missing something here, but the ResultSet is also from a different project -> io.vertx.ext.sql 

So, inorder to make it compatible, I would require to maintain 3 different projects, which I donot want to do.

Could you please share your workaround so that I could have a look at it.

**Comment by pmlopes** [comment]
@buddhashrestha @romanpa would you like to review #82 

This is a minimal impact change that will not affect existing code or interfere with the async client.

**Comment by romanpa** [comment]
Hi

Thanks for prompt response.
Looks nice.
Will it be included in upcoming Vertx release?

**Comment by buddhashrestha** [comment]
Yup. Thanks for the quick impl. This worked for me.

**Comment by pmlopes** [comment]
After a proper review and acceptance from the community it should.
