### ISSUE TITLE
Vertx async stalling out with await and JDBCClient callback.

### ISSUE THREAD

**Issue by bhowell2** [vert-x3/vertx-jdbc-client#86]
I'm having quite a few problems with vertx-unit with vertx-jdbc-client.
A reproducer has been provided (below), it uses embedded postgres, postgres JDBC driver, and vertx 3.4.0-SNAPSHOT vertx stuff.
When using Async with JDBCClient, the test is stalling out until the timeout fires. 
```java
   Async async = testContext.async();
   postgresClient.getConnection(result -> {
     if (result.succeeded()) {

     }
     System.out.println(async.count());
     async.countDown();
   });
   async.await(3000); // Errors out here, but if you check STD OUT, it prints async.count
```

However, there is no problem when using this code:
```java
    Async async = testContext.async();
   postgresClient.getConnection(result -> {
     if (result.succeeded()) {

     }
     async.complete();
   });
// NOTE: async.await, async.awaitSuccess and async.awaitSuccess(withTime) here would stall out as well.
```

Reproduce: 
Quite the simple reproducer here: https://github.com/bhowell2/VertxUnitAndJDBCClientIssue.
It uses an embedded postgres to facilitate the testing.

It's like JDBCClient is using the same thread as Async and Async is blocking the client from calling the handler (maybe the print statement is getting printed after the error is thrown).

**Comment by cescoffier** [comment]
Hi,

First, it's not really an "issue", so you should ask the question on the
Vert.x Google group.

In your code. I see several issues. You need to add the JDBC driver to your
classpath:

testCompile  "org.postgresql:postgresql:9.4.1212"

Then, you are using the "RunOnContext" rule. With this rule enabled, the
test runs on the event loop, and you must never block the event loop.
`async.await` blocks the event loop. Just use the `async.complete()` method
when your test is completed:

@Test(timeout = 2000)
  public void testConnectionTimesOut(TestContext testContext) {
    Async async = testContext.async();
   postgresClient.getConnection(result -> {
     if (result.succeeded()) {
       async.complete();
     } else {
       testContext.fail();
     }
   });
  }

If your goal is to configure a timeout for a test, use the "timeout"
parameter of @Test.



2017-01-30 3:47 GMT+01:00 Blake <notifications@github.com>:

**Comment by bhowell2** [comment]
Hi Clement,

Thanks for your response. Blocking the event loop is quite an embarrassing and major oversight on my part!

Also, forgot to re-push the github example with the driver, but it was there in my tests.
