### ISSUE TITLE
Support for getMetaData

### ISSUE THREAD

**Issue by jakefeasel** [vert-x3/vertx-jdbc-client#90]
### Version

* vert.x core: 3.1.0
* vert.x jdbc-client: 3.1.0
* jdbc driver: mysql-connector-java-5.1.31.jar
* RDBMS: mysql  Ver 14.14 Distrib 5.7.10, for osx10.10 (x86_64) using  EditLine wrapper

I am trying to get access to the meta data for my SQLConnection, and it seems this is unavailable. This is the function I'm interested in : 

https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#getMetaData--

I don't see any way to either get direct access to the underlying sql connection, nor to access this method via the vertx SQL Connection. It would be a useful improvement if this method were available.

**Comment by pmlopes** [comment]
This is not available out of the box since the SQL API is supposed to be generic and is shared both by JDBC and non-JDBC clients. As an possible improvement we could enhance the base Connection API to return the raw underlying connection object, so in this case you would get a `java.sql.Connection` and on the non-JDBC ones you would get something else...

**Comment by jakefeasel** [comment]
Having access to the underlying connection would be perfect.

**Comment by jakefeasel** [comment]
Did this commit make it into 3.4.2? Based on the commit history it looks to me like it did, and yet when I look within the decompiled class that ships with vert.x 3.4.2 the "nativeConnection" method is not available within JDBCConnectionImpl. Naturally, I can't call it either - 

```
Unhandled exception 
groovy.lang.MissingPropertyException: No such property: nativeConnection for class: io.vertx.ext.jdbc.impl.JDBCConnectionImpl

```

**Comment by vietj** [comment]
it has been renamed to `unwrap`

**Comment by vietj** [comment]
_native_ has a special meaning for Java and usually we tend rather to use `unwrap` across the Vert.x API when it comes to get the underlying object

**Comment by jakefeasel** [comment]
Thanks, this works perfectly! I've already gotten more use out of this method than I originally planned for. Cheers!
